name: Build and deploy

on:
  push:
    branches: [main]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .ssh directory
        run: mkdir ~/.ssh && chmod 700 ~/.ssh

      - name: Install deploy key & set permissions
        run: echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/deploy && chmod 600 ~/.ssh/deploy

      - name: Create known hosts
        run: echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Install dependencies
        run: cd $GITHUB_WORKSPACE && npm install

      - name: Build for production
        run: npm run build

      - name: Deploy
        run: ssh -i ~/.ssh/deploy deployer@ozzythepainter.com
